version: "3.9"

services:
  user_pool_web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - env/docker/auth.env
      - env/docker/postgres.env
      - env/docker/redis.env
    depends_on:
      redis_storage:
        condition: service_started
      postgres_storage:
        condition: service_healthy

  redis_storage:
    image: "redis"
    ports:
      - 6379:6379

  postgres_storage:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - env/docker/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      retries: 10
